import { Inject, Injectable, ConflictException } from '@nestjs/common';
import { User } from '../../../domain/entities/user.entity';
import {
  IUserRepository,
  USER_REPOSITORY,
} from '../../../domain/repositories/user.repository.interface';
import { BcryptService } from '../../../infrastructure/auth/bcrypt.service';

export interface RegisterUserCommand {
  email: string;
  password: string;
  name: string;
}

@Injectable()
export class RegisterUserUseCase {
  constructor(
    @Inject(USER_REPOSITORY)
    private readonly userRepository: IUserRepository,
    private readonly bcryptService: BcryptService,
  ) {}

  async execute(command: RegisterUserCommand): Promise<User> {
    // Check if user already exists
    const exists = await this.userRepository.exists(command.email);
    if (exists) {
      throw new ConflictException('User with this email already exists');
    }

    // Hash password
    const passwordHash = await this.bcryptService.hash(command.password);

    // Create domain entity
    const user = new User(
      null, // ID will be generated by repository
      command.email,
      passwordHash,
      command.name,
    );

    // Persist
    return this.userRepository.create(user);
  }
}
